### PR TITLE
feat(core): adds DAIPHP price id

### PR DESCRIPTION
**Pull request by schystz**
**Motivation**

Our desired price id DAI:PHP is not available yet, thus this PR to add the id in Kovan

**Summary**

Added `DAIPHP` to `packages/core/config/identifiers.json`

**Details**

Added `DAIPHP` to `packages/core/config/identifiers.json`

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [x]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

https://github.com/UMAprotocol/protocol/issues/2474

### CODE REVIEW

**Comment by daywiss** [comment]
@mrice32 I'm not familiar with what this file is for or if there is any additional updates needed here, like umip acceptance or pricefeed configuration?

**Review by nicholaspai — APPROVED** [review]
LGTM

**Review by mrice32 — APPROVED** [review]

**Comment by mrice32** [comment]
@schystz could you merge master into your branch? That should fix the test job.

**Comment by mrice32** [comment]
@schystz also, I've just added it to our kovan contracts, so it should be usable there now. But please follow the above steps to get this PR merged as well so it's documented in the repo.

**Comment by schystz** [comment]
@mrice32 I rebased the branch to master but unfortunately slither still fails

**Comment by mrice32** [comment]
> @mrice32 I rebased the branch to master but unfortunately slither still fails

No problem! Slither is broken right now, so it's not required to merge.

**Comment by schystz** [comment]
> > @mrice32 I rebased the branch to master but unfortunately slither still fails
> 
> @schystz No problem! Slither is broken right now, so it's not required to merge. `test` just needs to pass (which I'm confident it will now that you've rebased).

Gotcha!

**Pull request merged**
