### PR TITLE
improve(insured-bridge-price-feed): Use constant RATE_MODEL from @uma/sdk package

### PR DESCRIPTION
**Pull request by nicholaspai**
**Motivation**

We should reduce instances where we hardcode this JSON object, and read from a single source.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [X]  All existing tests pass
- [ ]  Untested

### CODE REVIEW

**Comment by nicholaspai** [comment]
@chrismaree do you think we should also import this constants file as a fallback value to `RATE_MODEL` in the `insured-bridge-relayer/RelayerConfig.ts` file?

**Comment by mrice32** [comment]
> @chrismaree do you think we should also import this constants file as a fallback value to `RATE_MODEL` in the `insured-bridge-relayer/RelayerConfig.ts` file?

@nicholaspai I think so, and I think ideally, we should usually be running the bots without overriding it. Thoughts?

**Review by mrice32 — APPROVED** [review]
LGTM!

**Comment by nicholaspai** [comment]
> > @chrismaree do you think we should also import this constants file as a fallback value to `RATE_MODEL` in the `insured-bridge-relayer/RelayerConfig.ts` file?
> 
> @nicholaspai I think so, and I think ideally, we should usually be running the bots without overriding it. Thoughts?

I'm good with that, my only concern is that currently updating the bot via a config file means that the bot can update very quickly. For example, if a new L1 token is causing the bot problems, then it can be removed instantly. 

However, requiring a change to pass CI takes longer so we'll have slower iteration speed. Thoughts?

**Comment by chrismaree** [comment]
> > > @chrismaree do you think we should also import this constants file as a fallback value to `RATE_MODEL` in the `insured-bridge-relayer/RelayerConfig.ts` file?
> > 
> > 
> > @nicholaspai I think so, and I think ideally, we should usually be running the bots without overriding it. Thoughts?
> 
> I'm good with that, my only concern is that currently updating the bot via a config file means that the bot can update very quickly. For example, if a new L1 token is causing the bot problems, then it can be removed instantly.
> 
> However, requiring a change to pass CI takes longer so we'll have slower iteration speed. Thoughts?

I do think we should pull from SDK for the bots. it should be configured such that this is the _default_ but we can always append to the config enabling us to move fast on the bots without updating the SDK. i.e best of both worlds

**Review by mrice32 — APPROVED** [review]
LGTM! Agree w this plan!

**Pull request merged**
