### PR TITLE
Update DefaultPriceFeedConfigs.ts - change the list of shares for uSPAC10

### PR DESCRIPTION
**Pull request by binomfx**
Signed-off-by: binomfx <binomfx@gmail.com>

Change shares list for uSPAC10.
Previously tested.

### CODE REVIEW

**Comment by binomfx** [comment]
Signed-off-by: binomfx <binomfx@fmail.com>

**Comment by daywiss** [comment]
i think theres a problem with the commits @binomfx. its included one of @amateima in this pr. let me try to update it

**Comment by amateima** [comment]
+1 for David's comment. The changes seem to be in sync with what is on the latest master version, but I recommend to rebase onto master in order to keep the PR clean

**Comment by binomfx** [comment]
I do not know how it happened. What should I do to fix it?

**Comment by daywiss** [comment]
this might be a bit complicated to fix. if your changes were just this line `symbols: ["DWAC", "IRDM", "PRIM", "TGLS", "MP", "LCID", "GDYN", "SMPL", "ENVX", "QS"],`.  id suggest you make sure you check out the latest master branch from upstream.  `git fetch upstream master`.  copy the changes you have made, then do a `git reset --hard upstream/master` and re-apply your changes manually.  make a new commit, `git commit -m 'fix: update default price feed configs'`, then `git push --force`

**Pull request closed without merging**
