### PR TITLE
Update mainnet addresses

### PR DESCRIPTION
**Pull request by mrice32**
Update the mainnet addresses to those that were created in UMIP-3.

### CODE REVIEW

**Comment by mrice32** [comment]
> LGTM but just one check: are these all checksum addresses?

Good thinking. Will double check.

**Comment by mrice32** [comment]
> > LGTM but just one check: are these all checksum addresses?
> 
> Good idea. Will double check.

@nicholaspai Just double checked all the new addresses -- they are the correct checksum addresses.

**Comment by nicholaspai** [comment]
> > > LGTM but just one check: are these all checksum addresses?
> > 
> > 
> > Good idea. Will double check.
> 
> @nicholaspai Just double checked all the new addresses -- they are the correct checksum addresses.

Awesome. WDYT about moving all the addresses to a `const` and force-checksumming them all before exporting the struct? Perhaps outside the scope of this PR but not a big change if we think that's a good idea.

**Comment by mrice32** [comment]
> > > > LGTM but just one check: are these all checksum addresses?
> > > 
> > > 
> > > Good idea. Will double check.
> > 
> > 
> > @nicholaspai Just double checked all the new addresses -- they are the correct checksum addresses.
> 
> Awesome. WDYT about moving all the addresses to a `const` and force-checksumming them all before exporting the struct? Perhaps outside the scope of this PR but not a big change if we think that's a good idea.

It’s used by the `apply-registry` tool, which only takes a `json`, so we I don’t think we can put any `js` in there.

**Pull request merged**
