### PR TITLE
added custom constant index for USD/ETH

### PR DESCRIPTION
**Pull request by hlambur**
with ETHUSD @ ~$175

### CODE REVIEW

**Comment by mrice32** [comment]
@hlambur Why not just make the numerator constant(1) and the denominator the barchart eth price?

**Comment by hlambur** [comment]
How do you do that?

**Comment by mrice32** [comment]
See https://github.com/UMAprotocol/protocol/pull/680. The json files allow a numerator and denominator, which allows us to set up price feeds that are the composition of two API feeds. I had to tweak how we're doing the division because we didn't anticipate values < 1.

**Comment by hlambur** [comment]
@mrice32 damn, that's super cool you can do that! I love it. Yes, please push #680.

**Pull request merged**
