### PR TITLE
improve(migration): remove unnecessary code from perpetual creator migration

### PR DESCRIPTION
**Pull request by pemulis**
Signed-off-by: John Shutt <john.d.shutt@gmail.com>

**Motivation**

Removes some code from the perpetual creator migration that isn't needed, after discussion with @mrice32.

**Summary**

* Removes code where collateral whitelist is added to the finder, since it should already be there.
* Removes code adding a TestnetERC20 to the whitelist, since it should already be added.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [x]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

https://github.com/UMAprotocol/protocol/issues/2441

### CODE REVIEW

**Review by mrice32 — APPROVED** [review]
Very nice!!

**Comment by mrice32** [comment]
> * [ ]   Ran end-to-end test, running the code as in production
> * [ ]   New unit tests created
> * [ ]   Existing tests adequate, no new tests required
> * [ ]   All existing tests pass
> * [x]   Untested

@pemulis would you not say that the existing tests are adequate since these migrations are used throughout the test suite?

**Review by nicholaspai — APPROVED** [review]
Good catch! This duplicate logic did not throw any errors but it did send useless transactions.

**Comment by pemulis** [comment]
@mrice32 Good point!

**Pull request merged**
