### PR TITLE
github templates: add issue and PR templates

### PR DESCRIPTION
**Pull request by mrice32**
These are essentially just the GH standard issue templates. Please add suggestions where you see fit!

### CODE REVIEW

**Comment by daywiss** [comment]
i think those are a pretty good starting point. i think maybe there may be something missing if we were to use GH for creating tasks I think of tasks as more well specified, as to what is needed and why, how to do it and how do you know when its done.  This is something we can circle back to if we start establishing more of a process.

**Comment by mrice32** [comment]
> i think those are a pretty good starting point. i think maybe there may be something missing if we were to use GH for creating tasks I think of tasks as more well specified, as to what is needed and why, how to do it and how do you know when its done. This is something we can circle back to if we start establishing more of a process.

@daywiss I'm not 100% sure how this works, but we you can have multiple issue templates each with their own links (the link will basically pre-load an issue creation form with that template loaded). Maybe we can create one that's specifically designed for UMA "tasks". Thoughts?

**Comment by daywiss** [comment]
Yea that is cool, i just dont know about adding it unless we actually want to officially put a process in place. I mean we can add it but unless we have everyone buy it, it may just go unused. May take an eng meeting to hash out if we all think its important enough.

Assuming though its a good idea, then yea i have some thoughts on how to structure an internal task ticket, basically in this format:
Why - what is the motivation for this task
How - thoughts on how to implement it
Resolution - what are the deliverables, or how can we verify task is done

As i mentioned before it may be useful to score these things based on difficulty or estimated time to completion. this has benefits for both planning as well as for retrospectives. It also forces devs to think about the problem carefully and get on same page.

**Comment by mrice32** [comment]
@daywiss 

> Yea that is cool, i just dont know about adding it unless we actually want to officially put a process in place. I mean we can add it but unless we have everyone buy it, it may just go unused. May take an eng meeting to hash out if we all think its important enough.

The nice thing about these templates is that if we set up the PR template _and_ the issue templates correctly, github should force you to start with one of these templates, so it's pretty difficult to just ignore the process. For instance, the PR template I just added will have a section for issues and a comment explaining that you should _always_ have at least one linked issue. But your point is well-taken around making sure that what we put in place is _valuable_ enough for people to really buy into it and are disciplined about it.

> Why - what is the motivation for this task
> How - thoughts on how to implement it
> Resolution - what are the deliverables, or how can we verify task is done

I'm going to go ahead and add these plus a difficulty/time score to both of the existing templates. We can discuss more next week, but I think these are good ideas to get the process going, and we can always change if we don't like it.

**Comment by mrice32** [comment]
@daywiss I've updated the templates. We have one issue template for bug reports and one for "tasks" which is the one we should be using internally. We could consider adding one for external feature requests, but I figured that might be a little much for now. I added your suggestions to the "task" template.

**Pull request merged**
