### PR TITLE
fix(gas-estimation): update json field check

### PR DESCRIPTION
**Pull request by mrice32**
**Motivation**

We should be checking for the same field that we're reading.

**Summary**

Modified the field we're checking for.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [x]  Untested

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]

**Review by chrismaree — APPROVED** [review]

**Comment by chrismaree** [comment]
rebasing off master should fix CI for you.

**Review by chrismaree — CHANGES_REQUESTED** [review]
This change actually breaks this utility on polygon and should not be merged!

See the response for the gas estimiator APIs that this utility uses:

1) mainnet ethereum:
```
{"safeLow":1,"standard":1.3,"fast":2.1,"fastest":7.5,"currentBaseFee":33.2,"recommendedBaseFee":67.4}
```
2) mainnet polygon:
```
{"safeLow":75,"standard":75,"fast":75,"fastest":75,"blockTime":2,"blockNumber":18186233}
```

In both of these the `fastest` keyword is there but the `recommendedBaseFee` is _only_ there on mainnet ethereum.


In fact this actually means that the hot fix that I added earlier in the week will have _broken_ this utility on mainnet polygon as this will return null for the `recommendedBaseFee`.

I saw this will working on the general EIP1559 support. I will send out a PR that will correct this mistake in the hot fix, followed by the general EIP1559 PR fix for the whole repo.

**Comment by chrismaree** [comment]
Please see https://github.com/UMAprotocol/protocol/pull/3322

**Comment by mrice32** [comment]
@chrismaree agree that polygon is broken. Closing.

**Pull request closed without merging**
