### PR TITLE
chore: add dispute assertion function to oov3 interface

### LINKED ISSUE #4668: Dispute Assertion function not in OOV3 interface
**Description**

The dispute assertion is not present in the oov3 interface but is implemented in the oov3. 

**Reproduction**

NA

**Expected Behavior**

NA

**Screenshots**

NA

**Version and OS Info**

 - OS: macOS
 - Browser: Arc
 - Version: ae65deda

**Additional Context**

Can open a PR shortly for this.

### PR DESCRIPTION
**Pull request by pedrovalido**
**Motivation**

Closes #4668 

**Summary**

Adding function to oov3 interface. 

**Details**

Recently integrated uma protocol at ethglobal istanbul and found out the oov3 interface didnt contain the disputeAssertion function and had to add it manually. 

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

No testing needed as this is just adding a function to an interface. ``forge build`` seems to throw no issues related to the added function.

**Issue(s)**

Fixes #4668

### CODE REVIEW

**Review by mrice32 — APPROVED** [review]
Nice catch, this was definitely an oversight. Thanks for adding this @pedrovalido!

Looks like the tests failed -- trying to figure out why.

**Comment by pedrovalido** [comment]
image
@mrice32 looks like it doesnt find the ``Test.sol`` file in the foundry lib. Not sure if this is a CI problem or not. Maybe the CI needs to do forge install do get the forge libs?

**Comment by pedrovalido** [comment]
trying to help but dont know a lot about your CI setup.

From the ci logs, looks like this file is failing to import ``Test.sol`` . 
image
It is a bit strange though. Im able to run everything locally and I have the file locally after setting up the repo. So, maybe something to do with the CI setup?

image

**Comment by mrice32** [comment]
We finally got to the bottom of the issue in ci. Sorry for the delay. I think if you merge master into your branch, it should work now. [This PR](https://github.com/UMAprotocol/protocol/pull/4679) should have fixed the issue.

**Comment by mrice32** [comment]
@pedrovalido We finally got to the bottom of the issue in ci. Sorry for the delay. I think if you merge master into your branch, it should work now. [This PR](https://github.com/UMAprotocol/protocol/pull/4679) should have fixed the issue.

**Comment by pedrovalido** [comment]
Merge and the checks pass now :) @mrice32

**Comment by daywiss** [comment]
thanks @pedrovalido and @mrice32!

**Pull request merged**
