### PR TITLE
improve(identifiers.json): adds 3 new price identifiers for testing on Kovan

### PR DESCRIPTION
**Pull request by meirbank**
Title: feat(identifiers.json): adds 3 new price identifiers for testing on Kovan

**Motivation**

Adding these identifiers for testing on Kovan per https://docs.umaproject.org/developers/emp-deployment

**Summary**

Adding these identifiers for testing on Kovan per https://docs.umaproject.org/developers/emp-deployment

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [*]  Untested

**Issue(s)**

https://docs.umaproject.org/developers/emp-deployment

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]
LGTM! Thanks for the PR. OOC, what are the longer explanation for these identifiers?

**Comment by mrice32** [comment]
@meirbank Updated the title of the PR to match the conventional commits expectations, just FYI!

**Review by mrice32 — APPROVED** [review]
Don't worry about fixing the slither job, but could you fix the DCO so we can merge? https://github.com/apps/dco

**Comment by mrice32** [comment]
@meirbank I've also added these to kovan so they should be usable! But we would still like to get this merged, so it's documented in the repo!

**Comment by mrice32** [comment]
@meirbank So sorry, we had another PR touch this file just ahead of yours. Could you merge master (or rebase onto master) into your branch and fix the conflict?

**Review by chrismaree — APPROVED** [review]

**Pull request merged**
