### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EdouardLvdl**
./scripts/publishPrices.sh must be run from the top level directory

### CODE REVIEW

**Comment by mrice32** [comment]
Thanks for doing this! I had to close and reopen both of your PRs to make CI run. Our settings were a little broken when you first opened them, but now they should be fixed.

**Comment by mrice32** [comment]
Could you merge the updated master branch? We fixed a CI issue this morning that will cause your PR to fail.

**Comment by EdouardLvdl** [comment]
> Could you merge the updated master branch? We fixed a CI issue this morning that will cause your PR to fail.

Can't merge without an approving review since I don't have write access

**Comment by mrice32** [comment]
See comments from #430.

**Comment by mrice32** [comment]
Thanks @EdouardLvdl - since you are our first contributor that's outside of our organization, we'll need you to also sign off on all of your commits to agree to the DCO. That basically means that all of your commits need to have this line at the end to indicate that you agree:
```
Signed-off-by: Edouard Lavidalle <edouardlavidalle@gmail.com>
```

**Comment by mrice32** [comment]
Hey @EdouardLvdl, if you merge the updated master into your branch (which will fix CI), we should be good to go! Thanks!

**Pull request merged**
