### PR TITLE
Add events for ending a sponsor and paying fees

### PR DESCRIPTION
**Pull request by ptare**
Signed-off-by: Prasad Tare <prasad.tare@gmail.com>

### CODE REVIEW

**Comment by nicholaspai** [comment]
Looks good to me

**Comment by ptare** [comment]
@mrice32 @nicholaspai Rerun from CircleCI stopped working for me again, can one of you try rerunning the failed CI stages?

**Comment by nicholaspai** [comment]
> @mrice32 @nicholaspai Rerun from CircleCI stopped working for me again, can one of you try rerunning the failed CI stages?

Think I got it re-running

**Comment by ptare** [comment]
Thanks Nick, saw that the checks passed!

**Pull request merged**
