### PR TITLE
fix: run jest directly in verbose mode

### PR DESCRIPTION
**Pull request by daywiss**
Signed-off-by: David <david@umaproject.org>

**Motivation**
Seems like CI fails during testing because the SDK testing output does not display anything for over 10 minutes.  

**Summary**
This bypasses tsdx testing, uses jest directly and does verbose output to prevent ci from thinking the process has hung. 

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [x]  All existing tests pass
- [ ]  Untested

### CODE REVIEW

**Review by mrice32 — COMMENTED** [review]
I think this is a good change!

Are you confident that this is the culprit? Are you able to reproduce the long output delays on your machine?

The reason I ask is that I want to understand if the testing mode is the problem or if there isn't some sort of non-deterministic deadlock in the tests that's causing it to hang _sometimes_ regardless of the verbosity.

Regardless of that, I think this is good to merge (jest seems preferable to the tsdx wrapper), just wanted to understand how confident we are that this fixes the issue.

**Comment by daywiss** [comment]
@mrice32 

> I think this is a good change!
> 
> Are you confident that this is the culprit? Are you able to reproduce the long output delays on your machine?
> 
> The reason I ask is that I want to understand if the testing mode is the problem or if there isn't some sort of non-deterministic deadlock in the tests that's causing it to hang sometimes regardless of the verbosity.
> 
> Regardless of that, I think this is good to merge (jest seems preferable to the tsdx wrapper), just wanted to understand how confident we are that this fixes the issue.

Not totally sure what the problem is.  i did notice locally that tests do take a long time, and theres a long period, like 1 minute while there is no output.  In CI, it shows this was timing out at 10 minutes, so yea its possible there is some kind of deadlock, but im not sure how that could happen since the tests are really basic.  I figured having more regular output would be a good attempt.

some more hints is that when i first pushed this change, Ci failed with a different issue:
```
@uma/sdk: FAIL src/stores/js-map/store.test.ts
@uma/sdk:   ● Test suite failed to run
@uma/sdk:     A jest worker process (pid=448) was terminated by another process: signal=SIGKILL, exitCode=null. Operating system logs may contain more information on why this occurred.
@uma/sdk:       at ChildProcessWorker._onExit (node_modules/jest-worker/build/workers/ChildProcessWorker.js:366:23)
```

Not seeing this locally, and seems like it coudl be something with the CI environment, so i fixed the number of processes to 1 during the test ( since jest can spin off multiple processes)

**Comment by daywiss** [comment]
since changing the number of test workers to 1, the sdk tests passed in the same amount of time it takes to run locally @mrice32 so maybe this was the culprit? still the problem was intermittent so i think its hard to be sure.

**Review by mrice32 — APPROVED** [review]
> Not totally sure what the problem is. i did notice locally that tests do take a long time, and theres a long period, like 1 minute while there is no output. In CI, it shows this was timing out at 10 minutes, so yea its possible there is some kind of deadlock, but im not sure how that could happen since the tests are really basic. I figured having more regular output would be a good attempt.

Does your local run pause at the same line as the ci one?

> since changing the number of test workers to 1, the sdk tests passed in the same amount of time it takes to run locally

This seems more promising, as parallelism is often the issue when seeing nondeterministic results. I doubt time is a big issue with this package (we run packages in parallel and I doubt this one is a bottleneck), so I suspect this will result in more stability without much impact to ci time.

**Comment by daywiss** [comment]
> Does your local run pause at the same line as the ci one?

Yes but not for nearly as long, only about a minute, as opposed to 10 minutes, then it floods with test results.  Since using verbose mode, the output is more constant.

**Pull request merged**
