### PR TITLE
feat: dvm2.0 votingv2 gas optimisations

### PR DESCRIPTION
**Pull request by md0x**
Signed-off-by: Pablo Maldonado <pablo@umaproject.org>

**Motivation**

Improve gas consumption of `VotingV2`

**Summary**

Some gas improvements:
- store array length when looping
- store in memory objects when loaded more than once from storage 
- added `unchecked_inc` to save extra gas in loops
- added `immutable` variables

[Improvements here](https://github.com/UMAprotocol/protocol/pull/4018#issuecomment-1178738191)

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [x]  All existing tests pass
- [ ]  Untested

**Issue(s)**

Fixes #XXXX

### CODE REVIEW

**Comment by md0x** [comment]
Gas savings so far:
```
  VotingV2 gas usage
Gas used variation for "Simple vote resolution": -2414
New gas used: 587486
    ✓ Simple vote resolution
Gas used variation for "Batches multiple commits into one": -26673
New gas used: 1029338
    ✓ Batches multiple commits into one
Gas used variation for "Batch reveal multiple commits": -2093
New gas used: 373093
    ✓ Batch reveal multiple commits
Gas used variation for "Voter doesn't vote in 100 rounds": -99029
New gas used: 7876709
    ✓ Voter doesn't vote in 100 rounds
```

**Review by mrice32 — APPROVED** [review]
LGTM!

**Review by chrismaree — APPROVED** [review]

**Comment by md0x** [comment]
Gas comparison VotingV2 vs Voting:

| Contract | Method |  Min |  Max |  Avg |
|--|--|--|--|--|
| VotingV2 | batchCommit | 234550 | 410552 | 322551 |
| Voting | batchCommit | 134385 | 203547 | 168966 |
| VotingV2 | batchReveal | - | - | 241749 |
| Voting | batchReveal | - | - | 264552 |
| VotingV2 | commitAndEmitEncryptedVote | 116431 | 247645 | 195239 |
| Voting | commitAndEmitEncryptedVote | 59407 | 83732 | 74079 |
| VotingV2 | commitVote | 110529 | 449948 | 247361 |
| Voting | commitVote | 65087 | 300564 | 124198 |
| VotingV2 | commitVote | 89047 | 336423 | 174325 |
| Voting | commitVote | 46572 | 91313 | 65431 |
| VotingV2 | executeUnstake | 96329 | 105929 | 103529 |
| VotingV2 | requestGovernanceAction | 241902 | 241938 | 241914 |
| VotingV2 | requestPrice | 266491 | 6177513 | 1752007 |
| Voting | requestPrice | 198328 | 6025587 | 1666396 |
| VotingV2 | requestPrice | 57085 | 245103 | 234442 |
| Voting | requestPrice | 59231 | 177321 | 173624 |
| VotingV2 | requestUnstake | 147879 | 170579 | 153554 |
| VotingV2 | revealVote | 78747 | 136058 | 116039 |
| Voting | revealVote | 91415 | 154499 | 137041 |
| VotingV2 | revealVote | 137595 | 393418 | 201813 |
| Voting | revealVote | 156060 | 411910 | 220284 |
| VotingV2 | setCurrentTime | 31889 | 31901 | 31901 |
| Voting | setCurrentTime | 31866 | 31878 | 31878 |
| VotingV2 | setGatPercentage | - | - | 29144 |
| Voting | setGatPercentage | 29148 | 29160 | 29151 |
| VotingV2 | setMigrated | - | - | 46127 |
| VotingV2 | setSlashingLibrary | - | - | 24011 |
| VotingV2 | setUnstakeCoolDown | - | - | 23867 |
| VotingV2 | stake | 106775 | 160255 | 120109 |
| VotingV2 | updateTrackers | 60505 | 364920 | 164528 |

**Comment by md0x** [comment]
Gas comparison VotingV2 vs Voting:

| Contract | Method |  Min |  Max |  Avg |
|--|--|--|--|--|
| VotingV2 | batchCommit | 234550 | 410552 | 322551 |
| Voting | batchCommit | 134385 | 203547 | 168966 |
| VotingV2 | batchReveal | - | - | 241749 |
| Voting | batchReveal | - | - | 264552 |
| VotingV2 | commitAndEmitEncryptedVote | 116431 | 247645 | 195239 |
| Voting | commitAndEmitEncryptedVote | 59407 | 83732 | 74079 |
| VotingV2 | commitVote | 110529 | 449948 | 247361 |
| Voting | commitVote | 65087 | 300564 | 124198 |
| VotingV2 | commitVote | 89047 | 336423 | 174325 |
| Voting | commitVote | 46572 | 91313 | 65431 |
| VotingV2 | executeUnstake | 96329 | 105929 | 103529 |
| VotingV2 | requestGovernanceAction | 241902 | 241938 | 241914 |
| VotingV2 | requestPrice | 266491 | 6177513 | 1752007 |
| Voting | requestPrice | 198328 | 6025587 | 1666396 |
| VotingV2 | requestPrice | 57085 | 245103 | 234442 |
| Voting | requestPrice | 59231 | 177321 | 173624 |
| VotingV2 | requestUnstake | 147879 | 170579 | 153554 |
| VotingV2 | revealVote | 78747 | 136058 | 116039 |
| Voting | revealVote | 91415 | 154499 | 137041 |
| VotingV2 | revealVote | 137595 | 393418 | 201813 |
| Voting | revealVote | 156060 | 411910 | 220284 |
| VotingV2 | setCurrentTime | 31889 | 31901 | 31901 |
| Voting | setCurrentTime | 31866 | 31878 | 31878 |
| VotingV2 | setGatPercentage | - | - | 29144 |
| Voting | setGatPercentage | 29148 | 29160 | 29151 |
| VotingV2 | setMigrated | - | - | 46127 |
| VotingV2 | setSlashingLibrary | - | - | 24011 |
| VotingV2 | setUnstakeCoolDown | - | - | 23867 |
| VotingV2 | stake | 106775 | 160255 | 120109 |
| VotingV2 | updateTrackers | 60505 | 364920 | 164528 |

**Pull request merged**
