### PR TITLE
improve(affiliates): add dev mining payout for week of 1/25

### LINKED ISSUE #2460: Run Dev Mining Rewards for week of 1/25
**Why**

EMP deployer rewards from 2020-01-18 23:00:00 to 2021-01-25 23:00:00 utc. This week sees a few additions and few removals.

Contract | EMP Address | Payout Address
-- | -- | --
pxUSD_MAR2021 | 0x3a93E863cb3adc5910E6cea4d51f132E8666654F | 0x53911776641d6dF38B88b9eF27f920c617E3Cb5e
uGAS-JAN21 | 0x516f595978D87B67401DaB7AfD8555c3d28a3Af4 | 0x97990B693835da58A281636296D2Bf02787DEa17
YD-BTC-MAR21 | 0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35
YD-ETH-MAR21 | 0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35
Zelda "Spring Nuts" USDC | 0xeAddB6AD65dcA45aC3bB32f88324897270DA0387  | 0xF53FBC3aDbe91E1A408716C0AF4C0cDC17A2cca8
Zelda "Summer Nuts" USDC | 0xf215778f3a5e7ab6a832e71d87267dd9a9ab0037 | 0xb8E237CC8D2E81b7C9C9C4B5877200f85100fC87
Zelda "Elastic" USDC | 0x267D46e71764ABaa5a0dD45260f95D9c8d5b8195 | 0x531B290230b1809d0AE29Ea834EdF96748F49Bf9
Zelda Whirlwind Cash |0x2862a798b3defc1c24b9c0d241beaf044c45e585 | 0xa1eD088d0789e7baBa18Ed4d87baca65376850d8
Zelda Reinforced Cash | 0xd81028a6fbaaaf604316f330b20d24bfbfd14478 | 0xdB0d599C3D49F6B349c83Dc2407a16F2830d6fCc
Mini Mario Cash  | 0x7c4090170aeADD54B1a0DbAC2C8D08719220A435 | 0x7eb1e51351380E67F641B84545bf41eCdc10298E
Mario Mini Spring Cache | 0xaD3cceebeFfCdC3576dE56811d0A6D164BF9A5A1 | 0x7eb1e51351380E67F641B84545bf41eCdc10298E
ALTDOM-MAR2021 | 0xC843538d70ee5d28C5A80A75bb94C28925bB1cf2 | DOMFINANCE
BTCDOM-MAR2021 | 0xeFA41F506EAA5c24666d4eE40888bA18FA60a1c7 | DOMFINANCE

Several of these will force default prices to 1
- 0xeAddB6AD65dcA45aC3bB32f88324897270DA0387
- 0xf215778f3a5e7ab6a832e71d87267dd9a9ab0037
- 0x267D46e71764ABaa5a0dD45260f95D9c8d5b8195
- 0x2862a798b3defc1c24b9c0d241beaf044c45e585
- 0xd81028a6fbaaaf604316f330b20d24bfbfd14478

### PR DESCRIPTION
**Pull request by daywiss**
Signed-off-by: David Adams <david@umaproject.org>

**Motivation**
#2460

**Summary**

Runs dev mining for week of 1/25

**Details**
This week relies on an update to dev mining code in #2463 before it can be ran. It also needs to be manually updated to include dom finance payout addresses.

In order to run create a config.json with this data:
```
{
    "empWhitelist": [
      ["0x3a93E863cb3adc5910E6cea4d51f132E8666654F", "0x53911776641d6dF38B88b9eF27f920c617E3Cb5e"],
      ["0x516f595978D87B67401DaB7AfD8555c3d28a3Af4", "0x97990B693835da58A281636296D2Bf02787DEa17"],
      ["0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0xeAddB6AD65dcA45aC3bB32f88324897270DA0387", "0xF53FBC3aDbe91E1A408716C0AF4C0cDC17A2cca8"],
      ["0xf215778f3a5e7ab6a832e71d87267dd9a9ab0037", "0xb8E237CC8D2E81b7C9C9C4B5877200f85100fC87"],
      ["0x267D46e71764ABaa5a0dD45260f95D9c8d5b8195", "0x531B290230b1809d0AE29Ea834EdF96748F49Bf9"],
      ["0x2862a798b3defc1c24b9c0d241beaf044c45e585", "0xa1eD088d0789e7baBa18Ed4d87baca65376850d8"],
      ["0xd81028a6fbaaaf604316f330b20d24bfbfd14478", "0xdB0d599C3D49F6B349c83Dc2407a16F2830d6fCc"],
      ["0x7c4090170aeADD54B1a0DbAC2C8D08719220A435", "0x7eb1e51351380E67F641B84545bf41eCdc10298E"],
      ["0xaD3cceebeFfCdC3576dE56811d0A6D164BF9A5A1", "0x7eb1e51351380E67F641B84545bf41eCdc10298E"],
      ["0xC843538d70ee5d28C5A80A75bb94C28925bB1cf2", "0xbca9B2e6B6620197aBA4fdb59079d3FeE21c361E"],
      ["0xeFA41F506EAA5c24666d4eE40888bA18FA60a1c7", "0xbca9B2e6B6620197aBA4fdb59079d3FeE21c361E"]
    ],
    "startTime": 1611010800000,
    "endTime": 1611615600000,
    "totalRewards": "50000",
    "network": 1,
    "fallbackPrices": [
      ["0xeAddB6AD65dcA45aC3bB32f88324897270DA0387", "1"],
      ["0xf215778f3a5e7ab6a832e71d87267dd9a9ab0037", "1"],
      ["0x267D46e71764ABaa5a0dD45260f95D9c8d5b8195", "1"],
      ["0x2862a798b3defc1c24b9c0d241beaf044c45e585", "1"],
      ["0xd81028a6fbaaaf604316f330b20d24bfbfd14478", "1"]
    ]
  }
```

Then run `node apps/DevMiningRewards.js config.json --network=mainnet_mnemonic`
**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [x]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [x]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

Fixes #2460

### CODE REVIEW

**Comment by smb2796** [comment]
The DomFin payout address should be the EMP deployer address: '0xbca9B2e6B6620197aBA4fdb59079d3FeE21c361E'.

**Comment by chrismaree** [comment]
I think you might need to re-base this PR against master. I have tried to re-run your tests but not sure if they will pass. if they fail, give that a go.

**Review by smb2796 — APPROVED** [review]
Other than the addition of the DomFin payout address, this looks good to me!

**Comment by daywiss** [comment]
> I think you might need to re-base this PR against master. I have tried to re-run your tests but not sure if they will pass. if they fail, give that a go.

@chrismaree this wont run on master. it needs to be run from the branch in #2463. I generated this file on that branch and pulled it into a PR on master so i could separate the changes.

**Comment by daywiss** [comment]
> Other than the addition of the DomFin payout address, this looks good to me!

Ive updated PR to reflect domfins payout address, thanks

**Comment by chrismaree** [comment]
> > I think you might need to re-base this PR against master. I have tried to re-run your tests but not sure if they will pass. if they fail, give that a go.
> 
> @chrismaree this wont run on master. it needs to be run from the branch in #2463. I generated this file on that branch and pulled it into a PR on master so i could separate the changes.

looks like it's passing now anyways 🤷

**Comment by hlambur** [comment]
Sent via tx: https://etherscan.io/tx/0x2a71df181a85b36a50d00415d29934f70999823633a69e1a405a28642f8e937c

**Pull request merged**
