### PR TITLE
Add copy of WETH9 and local migration for it

### PR DESCRIPTION
**Pull request by ptare**
Issue #1040

Signed-off-by: Prasad Tare <prasad.tare@gmail.com>

### CODE REVIEW

**Comment by ptare** [comment]
Prettier incompatibility between local runs and CI.

**Comment by ptare** [comment]
@chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!

**Comment by mrice32** [comment]
> @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!

Seeing the same issue on my local machine. Will investigate.

**Comment by chrismaree** [comment]
> @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!

I just pulled and ran lint and it worked fine which is curious.

**Comment by mrice32** [comment]
> > @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!
> 
> I just pulled and ran lint and it worked fine which is curious.

@ptare this is the diff it wants to apply:
```
diff --git a/core/contracts/financial-templates/implementation/WETH9.sol b/core/contracts/financial-templates/implementation/WETH9.sol
index b3cf1bd..7fa0624 100644
--- a/core/contracts/financial-templates/implementation/WETH9.sol
+++ b/core/contracts/financial-templates/implementation/WETH9.sol
@@ -39,11 +39,11 @@ contract WETH9 {
     mapping(address => uint) public balanceOf;
     mapping(address => mapping(address => uint)) public allowance;
 
-    receive() external payable {
+    function() external payable {
         deposit();
     }
 
-    fallback() external payable {
+    function() external payable {
         deposit();
     }
```

This feels like a solidity versioning thing. I have no idea why our local machines aren't changing it, though.

**Comment by ptare** [comment]
> > > @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!
> > 
> > 
> > I just pulled and ran lint and it worked fine which is curious.
> 
> @ptare this is the diff it wants to apply:
> 
> ```
> diff --git a/core/contracts/financial-templates/implementation/WETH9.sol b/core/contracts/financial-templates/implementation/WETH9.sol
> index b3cf1bd..7fa0624 100644
> --- a/core/contracts/financial-templates/implementation/WETH9.sol
> +++ b/core/contracts/financial-templates/implementation/WETH9.sol
> @@ -39,11 +39,11 @@ contract WETH9 {
>      mapping(address => uint) public balanceOf;
>      mapping(address => mapping(address => uint)) public allowance;
>  
> -    receive() external payable {
> +    function() external payable {
>          deposit();
>      }
>  
> -    fallback() external payable {
> +    function() external payable {
>          deposit();
>      }
> ```
> 
> This feels like a solidity versioning thing. I have no idea why our local machines aren't changing it, though.

Looks like prettier on the server is busted. The `function()` approach doesn't even compile for me.

Do you know how to disable the rule? Or another workaround?

**Comment by mrice32** [comment]
> > > > @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!
> > > 
> > > 
> > > I just pulled and ran lint and it worked fine which is curious.
> > 
> > 
> > @ptare this is the diff it wants to apply:
> > ```
> > diff --git a/core/contracts/financial-templates/implementation/WETH9.sol b/core/contracts/financial-templates/implementation/WETH9.sol
> > index b3cf1bd..7fa0624 100644
> > --- a/core/contracts/financial-templates/implementation/WETH9.sol
> > +++ b/core/contracts/financial-templates/implementation/WETH9.sol
> > @@ -39,11 +39,11 @@ contract WETH9 {
> >      mapping(address => uint) public balanceOf;
> >      mapping(address => mapping(address => uint)) public allowance;
> >  
> > -    receive() external payable {
> > +    function() external payable {
> >          deposit();
> >      }
> >  
> > -    fallback() external payable {
> > +    function() external payable {
> >          deposit();
> >      }
> > ```
> > 
> > 
> > This feels like a solidity versioning thing. I have no idea why our local machines aren't changing it, though.
> 
> Looks like prettier on the server is busted. The `function()` approach doesn't even compile for me.
> 
> Do you know how to disable the rule? Or another workaround?

Not sure, looking into it now.

**Comment by ptare** [comment]
> > > > > @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!
> > > > 
> > > > 
> > > > I just pulled and ran lint and it worked fine which is curious.
> > > 
> > > 
> > > @ptare this is the diff it wants to apply:
> > > ```
> > > diff --git a/core/contracts/financial-templates/implementation/WETH9.sol b/core/contracts/financial-templates/implementation/WETH9.sol
> > > index b3cf1bd..7fa0624 100644
> > > --- a/core/contracts/financial-templates/implementation/WETH9.sol
> > > +++ b/core/contracts/financial-templates/implementation/WETH9.sol
> > > @@ -39,11 +39,11 @@ contract WETH9 {
> > >      mapping(address => uint) public balanceOf;
> > >      mapping(address => mapping(address => uint)) public allowance;
> > >  
> > > -    receive() external payable {
> > > +    function() external payable {
> > >          deposit();
> > >      }
> > >  
> > > -    fallback() external payable {
> > > +    function() external payable {
> > >          deposit();
> > >      }
> > > ```
> > > 
> > > 
> > > This feels like a solidity versioning thing. I have no idea why our local machines aren't changing it, though.
> > 
> > 
> > Looks like prettier on the server is busted. The `function()` approach doesn't even compile for me.
> > Do you know how to disable the rule? Or another workaround?
> 
> Not sure, looking into it now.

Sorry to make you the designated prettier expert :(

**Comment by mrice32** [comment]
> > > > > > @chrismaree @nicholaspai Can one of please you download this branch, run prettier, and push the diff? I can't get my local prettier to make whatever change prettier on CI wants. Thanks!
> > > > > 
> > > > > 
> > > > > I just pulled and ran lint and it worked fine which is curious.
> > > > 
> > > > 
> > > > @ptare this is the diff it wants to apply:
> > > > ```
> > > > diff --git a/core/contracts/financial-templates/implementation/WETH9.sol b/core/contracts/financial-templates/implementation/WETH9.sol
> > > > index b3cf1bd..7fa0624 100644
> > > > --- a/core/contracts/financial-templates/implementation/WETH9.sol
> > > > +++ b/core/contracts/financial-templates/implementation/WETH9.sol
> > > > @@ -39,11 +39,11 @@ contract WETH9 {
> > > >      mapping(address => uint) public balanceOf;
> > > >      mapping(address => mapping(address => uint)) public allowance;
> > > >  
> > > > -    receive() external payable {
> > > > +    function() external payable {
> > > >          deposit();
> > > >      }
> > > >  
> > > > -    fallback() external payable {
> > > > +    function() external payable {
> > > >          deposit();
> > > >      }
> > > > ```
> > > > 
> > > > 
> > > > This feels like a solidity versioning thing. I have no idea why our local machines aren't changing it, though.
> > > 
> > > 
> > > Looks like prettier on the server is busted. The `function()` approach doesn't even compile for me.
> > > Do you know how to disable the rule? Or another workaround?
> > 
> > 
> > Not sure, looking into it now.
> 
> Sorry to make you the designated prettier expert :(

Oh, we're just behind on the pretter solidity plugin version. Seems to be fixed in `1.0.0-alpha.46`. So all you should need to do is upgrade that version.

**Comment by mrice32** [comment]
lol that shoulda been the first thing I checked.

**Comment by mrice32** [comment]
@ptare lmk if that doesn't work.

**Pull request merged**
