### PR TITLE
improve(affiliates): 2020-12-21 dev mining rewards week 7

### LINKED ISSUE #2358: EMP deployer/dev mining rewards for 7th week from 2020-12-21 23:00:00 to 2020-12-28 23:00:00
**Why**

EMP deployer rewards for 7th week from 2020-12-21 23:00:00 to 2020-12-28 23:00:00

Contract | EMP Address | Payout Address
-- | -- | --
uUSDwETH-DEC | 0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35
uUSDrBTC-DEC | 0xaBBee9fC7a882499162323EEB7BF6614193312e3 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35
pxUSD_MAR2021 | 0x3a93E863cb3adc5910E6cea4d51f132E8666654F | 0x53911776641d6dF38B88b9eF27f920c617E3Cb5e
uGAS-JAN21 | 0x516f595978D87B67401DaB7AfD8555c3d28a3Af4 | 0x97990B693835da58A281636296D2Bf02787DEa17
Mario Cash-JAN-2021 | 0x4aa79c00240a2094ff3fa6cf7c67f521f32d84a2 | 0x7eb1e51351380E67F641B84545bf41eCdc10298E 
BCHNrBTC-JAN-2021 | 0xf32219331a03d99c98adf96d43cc312353003531 | 0x37a0b32e07CD0b53AFb2981Cf02A74e10B80B577 
YD-BTC-MAR21 | 0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35
YD-ETH-MAR21 | 0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**

#2358

**Summary**
Ran dev mining rewards for 2020-12-21 through 2020-12-28.

**Details**
To reproduce, create a config file: `week7-config.json`

```
{
    "empWhitelist": [
      ["0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0xaBBee9fC7a882499162323EEB7BF6614193312e3", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0x3a93E863cb3adc5910E6cea4d51f132E8666654F", "0x53911776641d6dF38B88b9eF27f920c617E3Cb5e"],
      ["0x516f595978D87B67401DaB7AfD8555c3d28a3Af4", "0x97990B693835da58A281636296D2Bf02787DEa17"],
      ["0x4AA79c00240a2094Ff3fa6CF7c67f521f32D84a2", "0x7eb1e51351380E67F641B84545bf41eCdc10298E"],
      ["0xf32219331A03D99C98Adf96D43cc312353003531", "0x37a0b32e07CD0b53AFb2981Cf02A74e10B80B577"],
      ["0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"]
    ],
    "startTime": 1608591600000,
    "endTime": 1609196400000,
    "totalRewards": "50000",
    "network": 1
}
```
Then run:
`node apps/DeployerRewards.js week7-config.json --network=mainnet_mnemonic`

**Issue(s)**

Fixes #2358

### CODE REVIEW

**Review by smb2796 — APPROVED** [review]
Double-checked addresses and they all look correct. Payout amounts also look proportionally correct.

**Review by chrismaree — APPROVED** [review]
LGTM!

**Comment by hlambur** [comment]
This have been sent.

**Comment by Aveesh52** [comment]
Awesome!

**Pull request merged**
