### PR TITLE
improve: add week4 deployer rewards

### LINKED ISSUE #2268: deployer rewards 2020-11-30 23:00:00 to 2020-12-7 23:00:00
**Why**

Deployer rewards for 4th week from 2020-11-30 23:00:00 to 2020-12-7 23:00:00. This week removes an expired contract and includes the new ugas
Whitelist:
- "0x3a93E863cb3adc5910E6cea4d51f132E8666654F", //pxUSD_MAR2021
- "0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56", //uUSDwETH-DEC
- "0xaBBee9fC7a882499162323EEB7BF6614193312e3", //uUSDrBTC-DEC
- "0x516f595978D87B67401DaB7AfD8555c3d28a3Af4", //uGAS-JAN21

Unfortunately we cannot include `"0x4aa79c00240a2094ff3fa6cf7c67f521f32d84a2", //Mario Cash-JAN-2021` and `"0xf32219331a03d99c98adf96d43cc312353003531", //BCHNrBTC-JAN-2021` due to synthetic addresses not being listed yet on coingecko or cryptowatch for proper synthetic price calculation.

**EDIT**
We can include the BCH mario.cash emps in this payout thanks to #2270. Thier reward address differs from deployer address and this will need to be manually updated in deployer rewards output for now

**How**

Setup config and run deployer reward script.

**Resolution**

PR rewards file

**Difficulty Score [1-10]**

- 2: ~30 minutes

### PR DESCRIPTION
**Pull request by daywiss**
Signed-off-by: David Adams <david@umaproject.org>

<!--
  Thanks for submitting a pull request!
  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.
-->

<!--
  Title
  Please include a concise title that briefly describes the change.
  Titles should follow https://www.conventionalcommits.org/.
  They should also be in the present simple tense.

  Examples:
  
  feat(dvm): adds a new function to compute voting rewards offchain
  fix(monitor): fixes broken link in liquidation log
  feat(voter-dapp): adds countdown timer component to the header
  build(solc): updates solc version to 0.6.12
  improve(emp-client): parallelizes web3 calls to improve performance

  For examples of other types (feat, fix, build, improve) and what they mean, take a look at the angular list:
  https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

  See https://github.com/UMAprotocol/protocol/blob/master/CONTRIBUTING.md#conventional-commits for more details on PR
  title expectations.
-->


**Motivation**

#2268 


**Summary**

Week 4 rewards.


**Details**

config.js
```
{
"empWhitelist": [                                                                                                                                                                                                               
  0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56",
  "0xaBBee9fC7a882499162323EEB7BF6614193312e3",
  "0x3a93E863cb3adc5910E6cea4d51f132E8666654F",
  "0x516f595978D87B67401DaB7AfD8555c3d28a3Af4",
  "0x4AA79c00240a2094Ff3fa6CF7c67f521f32D84a2",
  "0xf32219331A03D99C98Adf96D43cc312353003531"
],
"startTime": 1606777200000,
"endTime": 1607382000000,
"totalRewards": "50000",
"network": 1
}
```
run `node apps/DeployerRewards.js config.js --network=mainnet_mnemonic`

**Important**
The output of the script has been manually modified to replace the deployer address for emps: `0x4AA79c00240a2094Ff3fa6CF7c67f521f32D84a2`  and `0xf32219331A03D99C98Adf96D43cc312353003531` with the preferred address specified by the mario.cash project: `0xF81d77768c6E82bAc26F994BB8C542586c05f1d1`. See notion doc here: https://www.notion.so/umaproject/Developer-Mining-836bb5a7091b4888a2c0c13e37f962dd

In the future the script will be updated to do this automatically. see #2271 

**Issue(s)**

<!-- This PR must fix or refer to one or more issues. Please list them here. -->
Fixes #2268

### CODE REVIEW

**Comment by daywiss** [comment]
There was a miscommunication with getting mario.cash and the bch emps to be included in this. They dont have listings for their synthetic contract on coingecko or cryptowatch. Wondering if we should delay payout and see if this can be added quickly for a recalc.

**Comment by daywiss** [comment]
hold off on payout, chris has an update #2270 which will allow mario.cash guys to participate in this weeks rewards! I will update this pr once that is merged

**Review by nicholaspai — APPROVED** [review]

**Comment by daywiss** [comment]
PR has been updated with the 2 BCH based EMPs @chrismaree @hlambur

**Review by chrismaree — APPROVED** [review]
Thanks for updating the PR. looks good to me! Payouts seem to be within the correct order of magnitude over the different emps.

**Comment by hlambur** [comment]
Non uUSD rewards were sent with this txs:
PERL https://etherscan.io/tx/0x466c43ecc106fa49ca13e57c6f1ec99654f9fed05fef1d5529f05d728d0d50ef
uGAS https://etherscan.io/tx/0x81afacc54731fcedfb7281e9410746fabd4d8e59e80ecaef02bc677d917b9c0f
Mario.Cash https://etherscan.io/tx/0x217462715af11c1e8b702383789c27db60ca6beeaba1b36e782e80400054f591

**Pull request merged**
