### PR TITLE
fix: fixes _minSponsorTokens description in contract docs

### PR DESCRIPTION
**Pull request by akhanubis**
**Motivation**

Param description in documentation refers to collateral when it should be synth tokens.

**Summary**

Fixed _minSponsorTokens description.

**Details**

Tiny change, although I'm not sure about the exact wording.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [X]  Untested

**Issue(s)**

N/A

### CODE REVIEW

**Review by mrice32 — APPROVED** [review]
LGTM! very nice catch

**Comment by mrice32** [comment]
@akhanubis, you'll need to pass DCO -- see here for details. Let me know if you have any problems and I'm happy to help you troubleshoot!

**Comment by akhanubis** [comment]
Done!

**Comment by mrice32** [comment]
> Done!

@akhanubis thanks! Just reran ci because we were having some issues this morning. Once it finishes, I think we can merge!

**Review by chrismaree — APPROVED** [review]

**Comment by chrismaree** [comment]
looks like this is still getting stuck in CI. I'm re-running it.

**Comment by chrismaree** [comment]
> looks like this is still getting stuck in CI. I'm re-running it.

Damn. This changes the contract byte code which breaks some tests :(

what you need to do is go to go to this file:
https://github.com/UMAprotocol/protocol/blob/master/packages/common/src/FindContractVersion.js

And update the lines for the byte code for the perp and the the EMP ([here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L63) and [here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L58)) to point to the correct byte code.

For the perp set this to: `0x7d16e88c724add0fe7203c01ddae5a36aa83d7a4bd32f4ce7e2d912ecf8bbfc8`
for the EMP set this to `0xd941d04649896343c11a906400392ea2da7c78e19737e148d555d7c7ad9b63d3`

**Comment by nicholaspai** [comment]
> > looks like this is still getting stuck in CI. I'm re-running it.
> 
> Damn. This changes the contract byte code which breaks some tests :(
> 
> what you need to do is go to go to this file:
> https://github.com/UMAprotocol/protocol/blob/master/packages/common/src/FindContractVersion.js
> 
> And update the lines for the byte code for the perp and the the EMP ([here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L63) and [here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L58)) to point to the correct byte code.
> 
> For the perp set this to: `0x7d16e88c724add0fe7203c01ddae5a36aa83d7a4bd32f4ce7e2d912ecf8bbfc8`
> for the EMP set this to `0xd941d04649896343c11a906400392ea2da7c78e19737e148d555d7c7ad9b63d3`

How is this changing the contract bytecode??

**Comment by chrismaree** [comment]
> > > looks like this is still getting stuck in CI. I'm re-running it.
> > 
> > 
> > Damn. This changes the contract byte code which breaks some tests :(
> > what you need to do is go to go to this file:
> > https://github.com/UMAprotocol/protocol/blob/master/packages/common/src/FindContractVersion.js
> > And update the lines for the byte code for the perp and the the EMP ([here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L63) and [here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L58)) to point to the correct byte code.
> > For the perp set this to: `0x7d16e88c724add0fe7203c01ddae5a36aa83d7a4bd32f4ce7e2d912ecf8bbfc8`
> > for the EMP set this to `0xd941d04649896343c11a906400392ea2da7c78e19737e148d555d7c7ad9b63d3`
> 
> How is this changing the contract bytecode??

comment changed in the `.sol` files. It's super sensitive to any code changes. Even just changing the structure of the repo can change the byte code.

**Comment by akhanubis** [comment]
> > what you need to do is go to go to this file:
> > https://github.com/UMAprotocol/protocol/blob/master/packages/common/src/FindContractVersion.js
> > And update the lines for the byte code for the perp and the the EMP ([here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L63) and [here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L58)) to point to the correct byte code.
> > For the perp set this to: `0x7d16e88c724add0fe7203c01ddae5a36aa83d7a4bd32f4ce7e2d912ecf8bbfc8`
> > for the EMP set this to `0xd941d04649896343c11a906400392ea2da7c78e19737e148d555d7c7ad9b63d3`


Should I go ahead and do that or has the bytecode already changed again because of new commits on master?

**Comment by chrismaree** [comment]
> > > what you need to do is go to go to this file:
> > > https://github.com/UMAprotocol/protocol/blob/master/packages/common/src/FindContractVersion.js
> > > And update the lines for the byte code for the perp and the the EMP ([here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L63) and [here](https://github.com/UMAprotocol/protocol/blob/69b87e98283b6970375358010d906f55fa29dd9b/packages/common/src/FindContractVersion.js#L58)) to point to the correct byte code.
> > > For the perp set this to: `0x7d16e88c724add0fe7203c01ddae5a36aa83d7a4bd32f4ce7e2d912ecf8bbfc8`
> > > for the EMP set this to `0xd941d04649896343c11a906400392ea2da7c78e19737e148d555d7c7ad9b63d3`
> 
> Should I go ahead and do that or has the bytecode already changed again because of new commits on master?

you'll need to do it still. This is why CI is failing on your PR. First, you need to rebase your PR onto master and then update the byte code. sorry for this pain in this part of the tooling!

**Comment by chrismaree** [comment]
Thanks for updating the PR! I'm re-running your unit tests now.

**Comment by akhanubis** [comment]
I'm fine with closing this PR, I can live with doc errors lol. Unless someone can give me the bytecode hash to use in FindContractVersion before it changes again.

**Comment by mrice32** [comment]
> I'm fine with closing this PR, I can live with doc errors lol. Unless someone can give me the bytecode hash to use in FindContractVersion before it changes again.

@akhanubis really sorry about this. We're going to fix this ci flakiness in the next day or so to make this process smoother :/

**Comment by chrismaree** [comment]
This PR has been blocked for a while! we actually have a fix for this `FindContractVersion` that, once merged, should unblock these issues! I'll report back once it's merged.

**Comment by chrismaree** [comment]
@akhanubis you should be able to now rebase master onto your branch and revert your changes made to `FinaContractVersion` and everything should work as expected :)

**Comment by akhanubis** [comment]
looks like it's finally good to merge!

**Pull request merged**
