### PR TITLE
Upgrade Solidity to 0.6.4

### PR DESCRIPTION
**Pull request by mrice32**

### CODE REVIEW

**Comment by mrice32** [comment]
@nicholaspai could you review this?

**Comment by nicholaspai** [comment]
Looking at the changelog since 0.6 it doesn't seem like there'd be any offenders, I guess just run CI see if that passes, then just quickly go through dApps and make sure they don't break.

**Comment by mrice32** [comment]
> Looks good, have you made sure 0.6.4 is compatible with all the dependencies I had to adjust on the 0.6 upgrade in #970 ?
> 
> * Truffle 5.1.14
> * OZ v3-beta
> * Prettier alpha42
> * solidity coverage 0.7.2
> * @drizzle/store
> 
> And you upgraded solidity-docgen

Generally it's safe to assume that minor version upgrades don't break most deps. ci seems to pass, so I think we can safely assume there are no incompatibility with our node tools. Will double check the dapps, though.

**Comment by mrice32** [comment]
> > Looks good, have you made sure 0.6.4 is compatible with all the dependencies I had to adjust on the 0.6 upgrade in #970 ?
> > 
> > * Truffle 5.1.14
> > * OZ v3-beta
> > * Prettier alpha42
> > * solidity coverage 0.7.2
> > * @drizzle/store
> > 
> > And you upgraded solidity-docgen
> 
> Generally it's safe to assume that minor version upgrades don't break most deps. ci seems to pass, so I think we can safely assume there are no incompatibility with our node tools. Will double check the dapps, though.

@nicholaspai verified that both dapps load fine.

**Pull request merged**
