### PR TITLE
improve(affiliates): add feb and march ugas contracts to the dev mining payout list

### PR DESCRIPTION
**Pull request by ethedev**
**Motivation**

Add later expiry (February, March) UGAS contracts to the dev mining payout list.

**Summary**

Added two new addresses to the list.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [x]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

N/A

### CODE REVIEW

**Review by daywiss — COMMENTED** [review]
verified these are the ugas-feb21 and ugas-mar21 contracts in notion. just want to verify with @sean these should be activated next payout?

**Comment by smb2796** [comment]
@daywiss `getHistoricalPricePeriods` needs to be included in the UniswapPriceFeed to include these

**Comment by chrismaree** [comment]
please update your PR title and description to conform to the [contributing guidelines](https://github.com/UMAprotocol/protocol/blob/master/CONTRIBUTING.md) for this repo.

**Comment by mrice32** [comment]
@chrismaree I updated the description and title.

@ethedev see my title and description for future reference!

**Comment by ethedev** [comment]
> @chrismaree I updated the description and title.
> 
> @ethedev see my title and description for future reference!

sure! thank you @chrismaree @mrice32

**Comment by mrice32** [comment]
> > @chrismaree I updated the description and title.
> > @ethedev see my title and description for future reference!
> 
> sure! thank you @chrismaree @mrice32

@ethedev can you merge master and fix DCO (sign off each commit)?

**Comment by daywiss** [comment]
we are still waiting for uniswap historical price feed support on this PR just FYI. sorry its taking a while.

**Comment by daywiss** [comment]
still trying to move this one along! not forgotten

**Comment by daywiss** [comment]
i think we are good with this very soon. just ran dev mining payouts today for these

**Review by daywiss — APPROVED** [review]

**Comment by chrismaree** [comment]
Are we good to merge this in now @daywiss ? 

@ethedev just looks like you need to sort out your DCO signing on your commits.

Your Slither issue seems to be blocking your PR. You need to update your branch to the head of master to fix this issue. Let me know if you need any help with this!

**Comment by ethedev** [comment]
this has been moved to #2635

**Pull request closed without merging**
