### PR TITLE
Update UMIP docs to match the UMIP repo

### PR DESCRIPTION
**Pull request by mrice32**
This is just to keep this doc in line with https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-1.md.

### CODE REVIEW

**Comment by adrianmcli** [comment]
The re-wording LGTM, but are we sure we want to re-order the two?

I think the ordering of having Approved prior to Final is because that's the order of the lifecycle:

Draft ⟶ Last Call ⟶ Approved ⟶ Final

**Comment by mrice32** [comment]
> The re-wording LGTM, but are we sure we want to re-order the two?
> 
> I think the ordering of having Approved prior to Final is because that's the order of the lifecycle:
> 
> Draft ⟶ Last Call ⟶ Approved ⟶ Final

There was a mix up previously. @allisonlu22 can correct me, but I believe the correct ordering is: draft, last call, final, then approved.

This has already been corrected here: https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-1.md. But I think we forgot to correct the docs site.

**Comment by adrianmcli** [comment]
@mrice32 I think we need to update the `Draft ⟶ Last Call ⟶ Approved ⟶ Final` under "What is the lifecycle of a UMIP?" as well then.

**Comment by adrianmcli** [comment]
See: https://github.com/UMAprotocol/UMIPs/pull/18

**Comment by mrice32** [comment]
> @mrice32 I think we need to update the `Draft ⟶ Last Call ⟶ Approved ⟶ Final` under "What is the lifecycle of a UMIP?" as well then. I can submit a PR.

Done.

**Pull request merged**
