### PR TITLE
feat: deploy to Blast Sepolia

### PR DESCRIPTION
**Pull request by pumpedlunch**
deployed sandboxed oracle environment to Blast Sepolia

### CODE REVIEW

**Review by Reinis-FRP — COMMENTED** [review]
Please also add missing:
- hardhat configuration in `packages/common/src/HardhatConfig.ts`
- RPC endpoint in `packages/common/src/ProviderUtils.ts`
- network details in `packages/common/src/PublicNetworks.ts`

For reference, you can check #4554 when Base Goerli was added

**Comment by pumpedlunch** [comment]
Updated additional config files as per Reinis' request.

Info gathered from:
https://docs.blast.io/building/network-information
https://testnet.blastscan.io/documentation/recipes/hardhat-verification (Block scanner apiUrl)

**Comment by Reinis-FRP** [comment]
> Updated additional config files as per Reinis' request.
> 
> Info gathered from: https://docs.blast.io/building/network-information https://testnet.blastscan.io/documentation/recipes/hardhat-verification (Block scanner apiUrl)

Great, all looks good, can you only run linter on `HardhatConfig.ts`

**Comment by pumpedlunch** [comment]
lint fixed. Thanks Reinis.

**Review by mrice32 — APPROVED** [review]
LGTM!

**Review by Reinis-FRP — APPROVED** [review]

**Pull request merged**
