### PR TITLE
fix: call update on gas estimator before sending transactions

### PR DESCRIPTION
**Pull request by mrice32**
**Motivation**

Minor trader fix to ensure the gas price estimation is updated before sending transactions.

**Summary**

Just added a few update calls.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [x]  All existing tests pass
- [ ]  Untested

**Issue(s)**

N/A

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]
Can we call this in the file that constructs the `DSProxyManager` and passes in the gasEstimator? This way we don't have to remember to `update` it before each method

**Comment by mrice32** [comment]
> Can we call this in the file that constructs the `DSProxyManager` and passes in the gasEstimator? This way we don't have to remember to `update` it before each method 

We could, but then it never gets re-updated in a looping bot, right?

**Comment by mrice32** [comment]
@nicholaspai this is somewhat moot anyway, because @chrismaree is going to overhaul the transaction management here anyway.

**Comment by mrice32** [comment]
Going to go ahead and merge so we can get the bot up and running. Happy to change in a follow up!

**Pull request merged**
