### PR TITLE
Adding configs for btc and eth 3m/6m basis

### PR DESCRIPTION
**Pull request by chicfilabae**
As requested by @smb2796 , here are the BTC and ETH 3m/6m configs.

### CODE REVIEW

**Review by mrice32 — APPROVED** [review]
LGTM!

None of these have been launched yet, right? So they will be launched with the new EMP that will use 18 decimal price feeds by default, correct?

**Comment by mrice32** [comment]
@chicfilabae you'll need to fix DCO. Happy to help debug if needed!

**Comment by chicfilabae** [comment]
@mrice32 

Whoops, forgot to do that. Fixed now.

"None of these have been launched yet, right? So they will be launched with the new EMP that will use 18 decimal price feeds by default, correct?"

Correct, was waiting to deploy until now for that purpose. So should be all good there

**Review by daywiss — APPROVED** [review]
this looks fine, but hard to ensure it works from viewing the diff.  going to approve, but it probably should be tested even if its just running it to see it works.

**Review by smb2796 — APPROVED** [review]
Tested these price feeds locally against a manual calculation and everything looks to check out!

**Pull request merged**
