### PR TITLE
improve(affiliates): deployer rewards week 5

### LINKED ISSUE #2295: deployer rewards 2020-12-7 23:00:00 to 2020-12-14 23:00:00
**Why**

Deployer rewards for 5th week from 2020-12-7 23:00:00 to 2020-12-14 23:00:00. 

Whitelist (with payout addresses):
| Contract | EMP Address | Payout Address |
|------------|---------------|---------------------|
| uUSDwETH-DEC  | 0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35 |
| uUSDrBTC-DEC | 0xaBBee9fC7a882499162323EEB7BF6614193312e3 | 0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35 |
| pxUSD_MAR2021 | 0x3a93E863cb3adc5910E6cea4d51f132E8666654F | 0x53911776641d6dF38B88b9eF27f920c617E3Cb5e |
| uGAS-JAN21 | 0x516f595978D87B67401DaB7AfD8555c3d28a3Af4 | 0xdD395050aC923466D3Fa97D41739a4ab6b49E9F5 |
| Mario Cash-JAN-2021 | 0x4aa79c00240a2094ff3fa6cf7c67f521f32d84a2 | 0xF81d77768c6E82bAc26F994BB8C542586c05f1d1 |
| BCHNrBTC-JAN-2021 | 0xf32219331a03d99c98adf96d43cc312353003531 | 0xF81d77768c6E82bAc26F994BB8C542586c05f1d1 |

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**

#2295

**Summary**

Week 5 deployer rewards. Run from 2020-12-07 23:00:00 UTC to 2020-12-14 23:00:00 UTC.

This is the first week run with explicit payout addresses for all EMPs.  Should independently verify these are the correct addresses. See #2295 for the description of which address are for which emp.

**Details**

`week5config.json`
```
{
    "empWhitelist": [
      ["0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0xaBBee9fC7a882499162323EEB7BF6614193312e3", "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"],
      ["0x3a93E863cb3adc5910E6cea4d51f132E8666654F", "0x53911776641d6dF38B88b9eF27f920c617E3Cb5e"],
      ["0x516f595978D87B67401DaB7AfD8555c3d28a3Af4", "0xdD395050aC923466D3Fa97D41739a4ab6b49E9F5"],
      ["0x4AA79c00240a2094Ff3fa6CF7c67f521f32D84a2", "0xF81d77768c6E82bAc26F994BB8C542586c05f1d1"],
      ["0xf32219331A03D99C98Adf96D43cc312353003531", "0xF81d77768c6E82bAc26F994BB8C542586c05f1d1"]
    ],
    "startTime": 1607382000000,
    "endTime": 1607986800000,
    "totalRewards": "50000",
    "network": 1
  }
```

To run
```
   node app/DeployerRewards week5config.json --network=mainnet_mnemonic
```

**Issue(s)**

Fixes #2295

### CODE REVIEW

**Comment by smb2796** [comment]
I verified the payout addresses and they all look correct. The sizing of the rewards looks generally correct to me as well.

**Review by smb2796 — APPROVED** [review]
I verified the payout addresses and they all look correct. The sizing of the rewards looks generally correct to me as well. Thanks David!

**Review by chrismaree — APPROVED** [review]
Looks good and the magnitude seems reasnoble! Have based LM off these outputs.

**Comment by daywiss** [comment]
thanks guys

**Pull request merged**
