### PR TITLE
improve(financial-templates-lib): Update OCEANUSD default price confi…

### PR DESCRIPTION
**Pull request by therealhexi**
**Motivation**

OCEANUSD price identifier has a Binance, Kraken, Bitz as the three default price config data sources. During the recent price dispute for OCEANUSD price identifier, the community has identified that Bittrex's volume is low, and the price significantly deviates from other exhangse. According to Coingecko, OCEAN/USDT on Bittrex represents only 0.06% of the total daily trading volume. On the other hand, OCEAN/USD on Kraken has 1.12% of daily trading volume, 20 X of what Bittrex has. We suggest to update the price config from OCEAN/USDT on Bittrex to OCEAN/USD on Kraken.

In fact, in UMIP-46, the three selected data sources are indeed Binance, Kraken, and Bitz. Bittrex did not belong to the list.

**Summary**

Update the price pair configuration here to Kraken, which is already supported.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [x]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

I will update manual script run result here as well

**Issue(s)**

https://github.com/UMAprotocol/protocol/issues/3009

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]
LGTM

**Comment by therealhexi** [comment]
Testing done:
/truffle exec ./packages/core/scripts/local/getHistoricalPrice.js --network mainnet_mnemonic --identifier USDOCEAN --time 1621878000

```
(kraken:oceanusd) Historical OHLC @ 1621878060
  - ✅ Open Price: 1.710278775440396784
  - ⚠️  If you want to manually verify the specific exchange prices, you can make a GET request to: 
  - https://api.cryptowat.ch/markets/kraken/oceanusd/ohlc?after=1621878060&before=1621878060&periods=60
  - This will return an OHLC data packet as "result", which contains in order: 
  - [CloseTime, OpenPrice, HighPrice, LowPrice, ClosePrice, Volume, QuoteVolume].
  - We use the OpenPrice to compute the median. Note that you might need to invert the prices for certain identifiers like USDETH.
```

truffle exec ./packages/core/scripts/local/getHistoricalPrice.js --network mainnet_mnemonic --identifier OCEANUSD --time 1621878000

```
(kraken:oceanusd) Historical OHLC @ 1621878060
  - ✅ Open Price: 0.5847
  - ⚠️  If you want to manually verify the specific exchange prices, you can make a GET request to: 
  - https://api.cryptowat.ch/markets/kraken/oceanusd/ohlc?after=1621878060&before=1621878060&periods=60
  - This will return an OHLC data packet as "result", which contains in order: 
  - [CloseTime, OpenPrice, HighPrice, LowPrice, ClosePrice, Volume, QuoteVolume].
  - We use the OpenPrice to compute the median. Note that you might need to invert the prices for certain identifiers like USDETH.
```

**Comment by daywiss** [comment]
@evaldofelipe it looks like this is stuck in ci

**Comment by evaldofelipe** [comment]
> @evaldofelipe it looks like this is stuck in ci

fixed @daywiss good to go!

**Comment by therealhexi** [comment]
What's the next step? Can maintainer help merge this request?

**Pull request merged**
