### PR TITLE
improve(emp): Disperse liquidation rewards in one transaction

### LINKED ISSUE #2159: EMP-Liquidatable: Disperse rewards in one transaction
**Why**

Same as #2149 but for the EMP

- 5: ~4 hours

### PR DESCRIPTION
**Pull request by nicholaspai**
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

**Motivation**

#2159

**Summary**

Mirrors #2152 which implemented this feature for the Perpetual. 

The liquidator and disputer logic and logging for withdrawing rewards had to change to match this new EMP interface. Additionally, the bot code now takes advantage of the latest event data to read the settled dispute price instead of having to query the DVM on-chain.

This PR is blocked by an ABI versioning strategy so that existing bots can continue to run on contracts with older ABI's.

To lock the existing ABIs, this PR points all packages at `@uma/core@1.2.0` on npm (rather than symlinked).

**Issue(s)**

Fixes #2159

### CODE REVIEW

**Comment by nicholaspai** [comment]
@daywiss @chrismaree @mrice32 This ABI change is breaking the affiliates test, on this [line](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js#L40) for example. It is trying to import the ABI from the `build` folder [here](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js#L4). Is there a way now to specify the ABI version?

**Review by mrice32 — APPROVED** [review]
LGTM!

**Review by chrismaree — APPROVED** [review]
This is great! happy to see this added to the emp.

**Comment by chrismaree** [comment]
> @daywiss @chrismaree @mrice32 This ABI change is breaking the affiliates test, on this [line](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js?rgh-link-date=2020-11-16T21%3A47%3A26Z#L40) for example. It is trying to import the ABI from the `build` folder [here](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js?rgh-link-date=2020-11-16T21%3A47%3A26Z#L4). Is there a way now to specify the ABI version?

For starters, we should update affiliates to pull using the `getAbi` for that test (the rest of the affiliates correctly uses this package, I think this one does not as it's a mocha test).

Regarding the ABI versioning, I believe that this functionality is just about ready but has yet to be fully implemented.

**Comment by nicholaspai** [comment]
> > @daywiss @chrismaree @mrice32 This ABI change is breaking the affiliates test, on this [line](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js?rgh-link-date=2020-11-16T21%3A47%3A26Z#L40) for example. It is trying to import the ABI from the `build` folder [here](https://github.com/UMAprotocol/protocol/blob/master/packages/affiliates/test/mocha/affiliates.js?rgh-link-date=2020-11-16T21%3A47%3A26Z#L4). Is there a way now to specify the ABI version?
> 
> For starters, we should update affiliates to pull using the `getAbi` for that test (the rest of the affiliates correctly uses this package, I think this one does not as it's a mocha test).
> 
> Regarding the ABI versioning, this was fully implemented here #2181. However, we need to update the bots & affiliates scripts to accommodate this new interface for `getAbi` to specify the version. Ideally, we should hold off on this PR until this is merged in.

Makes sense, we should work on that soon though because this PR should be in before Nov 30

**Pull request merged**
